version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs  # See pyproject.toml > project.optional-dependencies > docs
    - method: setuptools
      path: .
